function ac = loadActivationCurve()
% loadActivationCurve  Load the pCa <-> activation mapping used by the model.
%
%   ac = loadActivationCurve() reads the vendored ActCurveSim120240819.mat and
%   returns a struct of griddedInterpolants that convert between pCa and
%   normalized fractional activation for each fiber type:
%
%     ac.pCaToActB / ac.actToPcaB   (bag)
%     ac.pCaToActC / ac.actToPcaC   (chain)
%     ac.pCaToActE / ac.actToPcaE   (extrafusal)
%
%   The raw curve (fields pCaList, fracBoundNormB/C/E) was generated by the
%   toolbox; this file is vendored under data/ so the tutorial is fully
%   self-contained. The interpolant construction mirrors createFineGrid.m from
%   gammaDriveOptimization.
%
%   These mappings are mainly used to (a) display "% activation" alongside pCa
%   and (b) parameterize the extrafusal muscle-tendon unit. The core intrafusal
%   simulation is driven in pCa directly (see makeGammaDrive).

persistent cache
if ~isempty(cache)
    ac = cache;
    return
end

s = load(resolveActCurve());

ac.pCaList = s.pCaList(:)';
ac.pCaToActB = fineGrid(s.pCaList, s.fracBoundNormB);
ac.actToPcaB = fineGrid(s.fracBoundNormB, s.pCaList);
ac.pCaToActC = fineGrid(s.pCaList, s.fracBoundNormC);
ac.actToPcaC = fineGrid(s.fracBoundNormC, s.pCaList);
ac.pCaToActE = fineGrid(s.pCaList, s.fracBoundNormE);
ac.actToPcaE = fineGrid(s.fracBoundNormE, s.pCaList);

cache = ac;
end

function out = fineGrid(x_coarse, y_coarse)
% Densify with a spline, then wrap in a linear griddedInterpolant for fast,
% monotone-safe lookups. griddedInterpolant needs strictly increasing sample
% points, so sort/uniquify first (activation curves can repeat at the ends).
x_coarse = x_coarse(:)';
y_coarse = y_coarse(:)';
[xu, ia] = unique(x_coarse, 'stable');
yu = y_coarse(ia);
[xs, order] = sort(xu);
ys = yu(order);
x_fine = linspace(min(xs), max(xs), 10000);
y_fine = interp1(xs, ys, x_fine, 'spline');
out = griddedInterpolant(x_fine, y_fine, 'linear', 'nearest');
end

function matFile = resolveActCurve()
% Locate the vendored activation curve, in dev AND in a compiled (deployed) app.
% In development the file sits at ../data/ relative to this function; when
% compiled with MATLAB Compiler the file is extracted under ctfroot, so we try
% several candidates and fall back to a recursive search.
name = 'ActCurveSim120240819.mat';
here = fileparts(mfilename('fullpath'));
cands = { fullfile(fileparts(here), 'data', name) };   % dev layout
if isdeployed
    cands{end+1} = fullfile(ctfroot, 'data', name);
    cands{end+1} = fullfile(ctfroot, 'spindleModelTutorial', 'data', name);
    cands{end+1} = fullfile(ctfroot, name);
end
for i = 1:numel(cands)
    if isfile(cands{i}), matFile = cands{i}; return; end
end
% Last resort: search the app tree for the file by name.
roots = {here};
if isdeployed, roots{end+1} = ctfroot; end
for k = 1:numel(roots)
    d = dir(fullfile(roots{k}, '**', name));
    if ~isempty(d), matFile = fullfile(d(1).folder, d(1).name); return; end
end
error('loadActivationCurve:missingData', ...
    'Could not locate %s (dev path: %s).', name, cands{1});
end
