function result = tutorialOptDemo(opts)
% tutorialOptDemo  Recover a B-spline gamma-drive from a simulated Ia.
%
%   result = tutorialOptDemo(opts) demonstrates the manuscript's gamma-drive
%   optimization workflow, end-to-end and self-contained. It reuses the REAL
%   functions from gammaDriveOptimization -- runSpindleSimForOpt_Bspline_5cp and
%   getIntrafusal_pCa_Bspline_5cp -- so the demo matches the published pipeline
%   (runOptimizedSimulation_HybridOpt_Bspline_5cp_grid.m), differing only in that
%   the target Ia is generated by the model itself (so the "true" answer is
%   known) instead of coming from experimental Taylor data.
%
%   What is represented (matching the manuscript):
%     - Extrafusal MTU: a sinusoidal (gait-cycle) length with alpha drive; the
%       fascicle length drives the intrafusal fibers. Computed ONCE (gamma drive
%       does not change it) and reused on every objective evaluation.
%     - Gamma static (chain): a periodic B-spline with 5 control points (in pCa)
%       plus a phase shift -- a flexible fusimotor waveform over the gait cycle.
%     - Gamma dynamic (bag): a phasic burst of magnitude x(1), with ON/OFF timing
%       held FIXED (the manuscript optimizes timing in an outer grid; here we fix
%       it and run the inner fmincon over magnitude + waveform, which is the part
%       that recovers cleanly).
%
%   Fitted vector x = [bagPca, cp1, cp2, cp3, cp4, cp5, phase]   (7 parameters).
%
%   opts (all optional):
%     .trueBagPca .trueCP(1x5) .truePhase   ground-truth parameters
%     .bag0 .cp0(1x5) .phase0               initial guess
%     .gDynOn .gDynOff                      fixed burst timing (% gait cycle)
%     .tEnd .maxIter                        horizon / iteration budget
%     .iterFcn                              callback(info) for live app updates
%
%   Requires gammaDriveOptimization on the path (see setupTutorialPaths). If it
%   is not found this function errors with guidance.

if ~exist('runSpindleSimForOpt_Bspline_5cp', 'file') || ...
   ~exist('getIntrafusal_pCa_Bspline_5cp', 'file')
    error('tutorialOptDemo:needGammaOpt', ...
        ['This demo reuses the manuscript B-spline functions from ', ...
         'gammaDriveOptimization, which are not on the path.\nClone ', ...
         'gammaDriveOptimization as a sibling folder, or set GAMMA_OPT_DIR.']);
end
if nargin < 1, opts = struct(); end

% -- Ground truth / guess / bounds -------------------------------------
trueBagPca = getOpt(opts, 'trueBagPca', 5.5);
trueCP     = getOpt(opts, 'trueCP',   [6.8 5.6 6.0 6.6 7.2]);
truePhase  = getOpt(opts, 'truePhase', 0.0);
bag0   = getOpt(opts, 'bag0',   7.0);
cp0    = getOpt(opts, 'cp0',    [6.5 6.5 6.5 6.5 6.5]);
phase0 = getOpt(opts, 'phase0', 0.0);

xTrue = [trueBagPca, trueCP(:)', truePhase];
x0    = [bag0,       cp0(:)',    phase0];
names = {'bagPca','cp1','cp2','cp3','cp4','cp5','phase'};

% -- Timing base --------------------------------------------------------
p = defaultTutorialParams();
p.protocol.type = 'sine';
cycle_period = 0.64;                    % s, one gait cycle (manuscript value)
MTUfreq  = 1 / cycle_period;
act_freq = MTUfreq;                     % gamma cycle == gait cycle
p.protocol.freq         = MTUfreq;
p.protocol.perturbStart = 0.3;
p.protocol.amplitude_pct = 8;
p.mtu.alphaMode = 'sine';               % alpha modulated over the gait cycle
p.mtu.alphaFreq = MTUfreq;
p.sim.tEnd = getOpt(opts, 'tEnd', 1.6);   % settle + ~2 gait cycles (kept short
                                          % so the interactive fit stays snappy)

dt = p.sim.dt;
t  = 0:dt:p.sim.tEnd;
sineStart = find(t >= p.protocol.perturbStart, 1, 'first');

gDynOn  = getOpt(opts, 'gDynOn', 10);   % % gait cycle
gDynOff = getOpt(opts, 'gDynOff', 60);

lb = [4.5, 4.5*ones(1,5), -cycle_period/2];
ub = [9.0, 9.0*ones(1,5),  cycle_period/2];
% patternsearch polls 2N points per iteration, so it needs more iterations than
% fmincon did. The manuscript allows 200 iterations / 400 evaluations per grid
% node; this default is smaller so an interactive fit still finishes in a couple
% of minutes - one of the differences listed in
% docs/07_differences_from_manuscript.md.
maxIter     = getOpt(opts, 'maxIter', 25);
iterFcn     = getOpt(opts, 'iterFcn', []);
useParallel = getOpt(opts, 'useParallel', false);  % parallel finite differences
% Solver. The manuscript uses PATTERNSEARCH ("derivative-free; reliable on the
% stepped cost"), so that is the default here too. fmincon/sqp is offered for
% comparison - on this cost it tends to stall on the weakly-identified chain
% control points, whose gradient is small next to the bag's.
solver = lower(getOpt(opts, 'solver', 'patternsearch'));
if strcmp(solver, 'patternsearch') && isempty(which('patternsearch'))
    solver = 'fmincon';   % Global Optimization Toolbox absent
end

% -- Activation interpolants (chain) -----------------------------------
ac = loadActivationCurve();
pCaToAct = ac.pCaToActC;
actToPca = ac.actToPcaC;

% -- Base fiber structs -------------------------------------------------
sarcB0 = getDefaultSarcB(); sarcB0.initial_pCa = 9;
sarcC0 = getDefaultSarcC();

% -- Preview mode -------------------------------------------------------
% The GUI draws the TRUE drive live as the user picks it. Returning here,
% before the expensive MTU solve, reuses this function's own timing
% constants and recoverGamma, so what the user previews can never drift
% from the waveform the fit is actually asked to recover.
if getOpt(opts, 'previewOnly', false)
    result = struct('gammaTrue', recoverGamma(xTrue), ...
                    'cycle_period', cycle_period);
    return
end

% -- Extrafusal MTU (compute once) -------------------------------------
mt = runExtrafusalMTU(t, p);
mtData = mt.mtData;

    function [r_t, r, rs, rd] = simulate(x)
        sB = sarcB0; sC = sarcC0;
        sB.activating_pCa = x(1);
        cp = x(2:6)';
        phase = x(7);
        [r_t, ~, ~, r, rs, rd] = runSpindleSimForOpt_Bspline_5cp( ...
            t, sineStart, MTUfreq, act_freq, sC, sB, gDynOn, gDynOff, ...
            cp, phase, mtData, pCaToAct, actToPca);
    end

% -- Target from truth --------------------------------------------------
[tgt_t, target] = simulate(xTrue);
% Cost is a single MEAN-NORMALIZED RMSE on the TOTAL receptor potential, exactly
% as the manuscript scores one recorded trace
% (objFuncWithFixedTiming_Bspline_5cp_normSmooth). See compute/meanNormRMSE.m.
%
% An earlier version scored rs and rd SEPARATELY. That recovered the parameters
% far better - but only because a self-generated target lets you decompose it
% into its static and dynamic parts. A real recording is one signal and cannot be
% split, so scoring the components separately was giving this demo information no
% experiment has, and flattering the result. Whatever identifiability the single
% combined signal supports is the honest answer, and is what this now shows.

    function c = objective(x)
        try
            [rt, rr] = simulate(x);
            fitR = interp1(rt(:), rr(:), tgt_t(:), 'linear', 'extrap');
            c = meanNormRMSE(fitR, target(:));
        catch
            c = 1e6;
        end
    end

% -- History + optimize -------------------------------------------------
history = struct('iter', {}, 'fval', {}, 'x', {});
    function [stop, opts2, chg] = psout(optimValues, opts2, flag)
        stop = false; chg = false;
        if strcmp(flag, 'iter')
            history(end+1) = struct('iter', optimValues.iteration, ...
                'fval', optimValues.fval, 'x', optimValues.x(:)');
            if ~isempty(iterFcn)
                iterFcn(struct('iter', optimValues.iteration, 'fval', optimValues.fval, ...
                               'x', optimValues.x(:)', 'names', {names}));
            end
        end
    end

    function stop = outfun(x, ov, state)
        stop = false;
        if strcmp(state, 'iter')
            history(end+1) = struct('iter', ov.iteration, 'fval', ov.fval, 'x', x(:)');
            if ~isempty(iterFcn)
                iterFcn(struct('iter', ov.iteration, 'fval', ov.fval, ...
                               'x', x(:)', 'names', {names}));
            end
        end
    end

fval0 = objective(x0);
switch solver
    case 'patternsearch'
        psOpts = optimoptions('patternsearch', 'Display', 'off', ...
            'MaxIterations', maxIter, 'MaxFunctionEvaluations', 2000, ...
            'OutputFcn', @psout, 'UseParallel', useParallel, ...
            'UseCompletePoll', true);
        [xOpt, fvalOpt] = patternsearch(@objective, x0, [], [], [], [], lb, ub, [], psOpts);
    otherwise
        options = optimoptions('fmincon', 'Algorithm', 'sqp', 'Display', 'off', ...
            'MaxIterations', maxIter, 'MaxFunctionEvaluations', 2000, ...
            'FiniteDifferenceStepSize', 1e-2, 'OutputFcn', @outfun, ...
            'UseParallel', useParallel);
        [xOpt, fvalOpt] = fmincon(@objective, x0, [], [], [], [], lb, ub, [], options);
end
result.solver = solver;

% -- Traces for plotting ------------------------------------------------
[t0, fit0]     = simulate(x0);
[tO, fitOpt]   = simulate(xOpt);

gammaTrue = recoverGamma(xTrue);
gammaOpt  = recoverGamma(xOpt);

    function g = recoverGamma(x)
        sB = sarcB0; sC = sarcC0;
        sB.activating_pCa = x(1);
        [sC, sB] = getIntrafusal_pCa_Bspline_5cp(t, sineStart, MTUfreq, act_freq, ...
            sC, sB, gDynOn, gDynOff, x(2:6)', x(7), pCaToAct, actToPca);
        g.t = t;
        g.chainPca = sC.pCa(:);      % gamma-static waveform (pCa)
        g.bagPca   = sB.pCa(:);      % gamma-dynamic burst (pCa)
        % control-point markers (at 0,20,40,60,80% of the cycle from perturbStart)
        g.controlTimes = t(sineStart) + x(7) + [0 .2 .4 .6 .8] * cycle_period;
        g.controlPca   = x(2:6)';
    end

% -- Assemble -----------------------------------------------------------
result.method   = 'bspline';
result.names    = names;
result.labels   = {'Bag burst pCa','CP1 (0%)','CP2 (20%)','CP3 (40%)', ...
                   'CP4 (60%)','CP5 (80%)','Phase (s)'};
result.xTrue    = xTrue;
result.x0       = x0;
result.xOpt     = xOpt;
result.lb       = lb;
result.ub       = ub;
result.history  = history;
result.t        = tgt_t(:);
result.target   = target(:);
result.fit0     = interp1(t0(:), fit0(:), tgt_t(:), 'linear', 'extrap');
result.fitOpt   = interp1(tO(:), fitOpt(:), tgt_t(:), 'linear', 'extrap');
result.fval0    = fval0;
result.fvalOpt  = fvalOpt;
% Recovery = how much of the INITIAL error the fit actually closed, not how
% close the answer is to truth relative to the bound range. The old form gave a
% parameter that never moved 80-98% simply because the bounds are wide, which
% flattered exactly the parameters the fit fails to identify. 0% now means "did
% not move", 100% means "nailed it", negative means "moved away".
initErr = abs(x0 - xTrue);
result.recoveryPct = 100 * (1 - abs(xOpt - xTrue) ./ initErr);
% A parameter that STARTED at the right answer has no error to close, so the
% fraction is undefined rather than 100%. Mark it NaN instead of dividing by ~0.
result.recoveryPct(initErr < 1e-3 * (ub - lb)) = NaN;
result.gammaTrue = gammaTrue;
result.gammaOpt  = gammaOpt;
result.cycle_period = cycle_period;
end


% ======================================================================
function v = getOpt(opts, field, default)
if isfield(opts, field) && ~isempty(opts.(field)), v = opts.(field); else, v = default; end
end
