function result = tutorialOptDemo(opts)
% tutorialOptDemo  Recover a B-spline gamma-drive from a simulated Ia.
%
%   result = tutorialOptDemo(opts) demonstrates the manuscript's gamma-drive
%   optimization workflow, end-to-end and self-contained. It reuses the REAL
%   functions from gammaDriveOptimization -- runSpindleSimForOpt_Bspline_5cp and
%   getIntrafusal_pCa_Bspline_5cp -- so the demo matches the published pipeline
%   (runOptimizedSimulation_HybridOpt_Bspline_5cp_grid.m), differing only in that
%   the target Ia is generated by the model itself (so the "true" answer is
%   known) instead of coming from experimental Taylor data.
%
%   What is represented (matching the manuscript):
%     - Extrafusal MTU: a sinusoidal (gait-cycle) length with alpha drive; the
%       fascicle length drives the intrafusal fibers. Computed ONCE (gamma drive
%       does not change it) and reused on every objective evaluation.
%     - Gamma static (chain): a periodic B-spline with 5 control points (in pCa)
%       plus a phase shift -- a flexible fusimotor waveform over the gait cycle.
%     - Gamma dynamic (bag), one of two forms (opts.gammaDynamic):
%         'pulse'   (default) a phasic burst of magnitude bagPca, with ON/OFF
%                   timing held FIXED (the manuscript optimizes timing in an
%                   outer grid; here it is fixed and only the inner fit runs).
%         'bspline' the manuscript's Figure 1D form: a periodic B-spline with 5
%                   control points (in pCa), like gamma static, with its phase
%                   held FIXED at 0 (the manuscript grids over it).
%                   Calls runSpindleSimForOpt_Bspline_5cp_gDynBspline.
%     - Cost: the manuscript's receptor-potential cost (rPotentialCost): r above
%       its no-drive baseline mean(r(1:10)), floored at 0, mean-normalized,
%       scored over gait phase (0, 1.5) after skipping the first cycle. The
%       self-generated target gets the same baseline subtraction and floor, so
%       it has a true zero like the recorded firing rate it stands in for.
%
%   Fitted vector x:
%     pulse:   [bagPca, cp1..cp5, phase]          (7 parameters)
%     bspline: [gd1..gd5, cp1..cp5, phase]        (11 parameters)
%
%   opts (all optional):
%     .gammaDynamic                         'pulse' (default) | 'bspline'
%     .trueBagPca .trueCP(1x5) .truePhase   ground-truth parameters (pulse)
%     .trueGD(1x5)                          ground-truth bag control points (bspline)
%     .bag0 .gd0(1x5) .cp0(1x5) .phase0     initial guess
%     .gDynOn .gDynOff                      fixed burst timing (% gait cycle)
%     .tEnd .maxIter                        horizon / iteration budget
%     .iterFcn                              callback(info) for live app updates
%
%   Requires gammaDriveOptimization on the path (see setupTutorialPaths). If it
%   is not found this function errors with guidance.

if ~exist('runSpindleSimForOpt_Bspline_5cp', 'file') || ...
   ~exist('getIntrafusal_pCa_Bspline_5cp', 'file')
    error('tutorialOptDemo:needGammaOpt', ...
        ['This demo reuses the manuscript B-spline functions from ', ...
         'gammaDriveOptimization, which are not on the path.\nClone ', ...
         'gammaDriveOptimization as a sibling folder, or set GAMMA_OPT_DIR.']);
end
if nargin < 1, opts = struct(); end

% -- Ground truth / guess / bounds -------------------------------------
gammaDynamic = lower(getOpt(opts, 'gammaDynamic', 'pulse'));
if ~ismember(gammaDynamic, {'pulse','bspline'})
    error('tutorialOptDemo:badGammaDynamic', ...
        'opts.gammaDynamic must be ''pulse'' or ''bspline'' (got ''%s'').', gammaDynamic);
end
isSpline = strcmp(gammaDynamic, 'bspline');
% Bag levels default LOW (~10% activation), the range the manuscript uses:
% the bag is strong, so a little gamma-dynamic goes a long way.
trueBagPca = getOpt(opts, 'trueBagPca', 8.4);
trueGD     = getOpt(opts, 'trueGD',   [9.0 8.4 8.7 9.0 9.0]);
trueCP     = getOpt(opts, 'trueCP',   [6.8 5.6 6.0 6.6 7.2]);
truePhase  = getOpt(opts, 'truePhase', 0.0);
bag0   = getOpt(opts, 'bag0',   7.5);
gd0    = getOpt(opts, 'gd0',    bag0 * ones(1,5));
cp0    = getOpt(opts, 'cp0',    [6.5 6.5 6.5 6.5 6.5]);
phase0 = getOpt(opts, 'phase0', 0.0);
gDynPhase = 0;   % bspline: the bag waveform's phase, held fixed (see above)

cpNames = {'cp1','cp2','cp3','cp4','cp5'};
if isSpline
    xTrue = [trueGD(:)', trueCP(:)', truePhase];
    x0    = [gd0(:)',    cp0(:)',    phase0];
    names = [{'gd1','gd2','gd3','gd4','gd5'}, cpNames, {'phase'}];
    nBag  = 5;
else
    xTrue = [trueBagPca, trueCP(:)', truePhase];
    x0    = [bag0,       cp0(:)',    phase0];
    names = [{'bagPca'}, cpNames, {'phase'}];
    nBag  = 1;
end

% -- Timing base --------------------------------------------------------
p = defaultTutorialParams();
p.protocol.type = 'sine';
cycle_period = 0.64;                    % s, one gait cycle (manuscript value)
MTUfreq  = 1 / cycle_period;
act_freq = MTUfreq;                     % gamma cycle == gait cycle
p.protocol.freq         = MTUfreq;
p.protocol.perturbStart = 0.3;
p.protocol.amplitude_pct = 8;
p.mtu.alphaMode = 'sine';               % alpha modulated over the gait cycle
p.mtu.alphaFreq = MTUfreq;
p.sim.tEnd = getOpt(opts, 'tEnd', 1.9);   % settle + 2.5 gait cycles: just long
                                          % enough to hold the whole scored window

dt = p.sim.dt;
t  = 0:dt:p.sim.tEnd;
sineStart = find(t >= p.protocol.perturbStart, 1, 'first');

gDynOn  = getOpt(opts, 'gDynOn', 10);   % % gait cycle
gDynOff = getOpt(opts, 'gDynOff', 60);

lb = [4.5*ones(1,nBag), 4.5*ones(1,5), -cycle_period/2];
ub = [9.0*ones(1,nBag), 9.0*ones(1,5),  cycle_period/2];
% The manuscript allows 200 iterations / 400 evaluations per grid node; this
% default is smaller so an interactive fit still finishes in a minute or two -
% one of the differences listed in docs/07_differences_from_manuscript.md.
maxIter     = getOpt(opts, 'maxIter', 25);
iterFcn     = getOpt(opts, 'iterFcn', []);
useParallel = getOpt(opts, 'useParallel', false);  % parallel polls / differences
if useParallel && ~hasParallelToolbox()
    useParallel = false;   % Parallel Computing Toolbox absent - run serial
end
% Solver. fmincon (sqp) is the DEFAULT. The manuscript uses patternsearch,
% derivative-free, which suited its old firing-rate cost (stepped, because the
% spike generator quantises the rate). The receptor-potential cost is smooth, and
% on it fmincon does far better here: 25 iterations reach cost 0.022 in 46 s,
% against patternsearch's 0.115 in 86 s. patternsearch is kept for comparison.
solver = lower(getOpt(opts, 'solver', 'fmincon'));
if strcmp(solver, 'patternsearch') && isempty(which('patternsearch'))
    solver = 'fmincon';   % Global Optimization Toolbox absent
end

% -- Activation interpolants (chain; bag for the B-spline form) --------
ac = loadActivationCurve();
pCaToAct = ac.pCaToActC;
actToPca = ac.actToPcaC;

% -- Base fiber structs -------------------------------------------------
sarcB0 = getDefaultSarcB(); sarcB0.initial_pCa = 9;
sarcC0 = getDefaultSarcC();

% -- Preview mode -------------------------------------------------------
% The GUI draws the TRUE drive live as the user picks it. Returning here,
% before the expensive MTU solve, reuses this function's own timing
% constants and recoverGamma, so what the user previews can never drift
% from the waveform the fit is actually asked to recover.
if getOpt(opts, 'previewOnly', false)
    result = struct('gammaTrue', recoverGamma(xTrue), ...
                    'cycle_period', cycle_period);
    return
end

% -- Extrafusal MTU (compute once) -------------------------------------
mt = runExtrafusalMTU(t, p);
mtData = mt.mtData;

    function [r_t, r, rs, rd] = simulate(x)
        sB = sarcB0; sC = sarcC0;
        cp = x(nBag+1:nBag+5)';
        phase = x(nBag+6);
        if isSpline
            [r_t, ~, ~, r, rs, rd] = runSpindleSimForOpt_Bspline_5cp_gDynBspline( ...
                t, sineStart, MTUfreq, act_freq, sC, sB, x(1:5)', gDynPhase, ...
                cp, phase, mtData, pCaToAct, actToPca, ac.pCaToActB, ac.actToPcaB);
        else
            sB.activating_pCa = x(1);
            [r_t, ~, ~, r, rs, rd] = runSpindleSimForOpt_Bspline_5cp( ...
                t, sineStart, MTUfreq, act_freq, sC, sB, gDynOn, gDynOff, ...
                cp, phase, mtData, pCaToAct, actToPca);
        end
    end

% -- Scored signal: r above its no-drive baseline -----------------------
% Both drive constructions force samples 1:10 silent, so mean(r(1:10)) is the
% receptor potential with no drive - the manuscript's baseline. See
% rPotentialCost for why it is subtracted.
nBaselineSamples = 10;
    function s = aboveBaseline(r)
        s = r(:) - mean(r(1:nBaselineSamples));
        s(s < 0) = 0;
    end

% -- Target from truth --------------------------------------------------
[tgt_t, rTarget] = simulate(xTrue);
target = aboveBaseline(rTarget);
% Scored window: gait phase (0, 1.5), counted from one cycle after the stretch
% starts, as the manuscript does - the first cycle is a start-up transient.
tOffset = t(sineStart) + cycle_period;
scoreWin = [tOffset, tOffset + 1.5*cycle_period];
inWin = tgt_t(:) > scoreWin(1) & tgt_t(:) < scoreWin(2);
% Cost is a single MEAN-NORMALIZED RMSE on the TOTAL receptor potential, as the
% manuscript scores one recorded trace. See compute/rPotentialCost.m.
%
% An earlier version scored rs and rd SEPARATELY. That recovered the parameters
% far better - but only because a self-generated target lets you decompose it
% into its static and dynamic parts. A real recording is one signal and cannot be
% split, so scoring the components separately was giving this demo information no
% experiment has, and flattering the result. Whatever identifiability the single
% combined signal supports is the honest answer, and is what this now shows.

    function c = objective(x)
        try
            [rt, rr] = simulate(x);
            fitR = interp1(rt(:), rr(:), tgt_t(:), 'linear', 'extrap');
            if nnz(inWin) < 5, c = 1e6; return; end
            c = rPotentialCost(fitR(inWin), target(inWin), mean(rr(1:nBaselineSamples)));
        catch
            c = 1e6;
        end
    end

% -- History + optimize -------------------------------------------------
history = struct('iter', {}, 'fval', {}, 'x', {});
    function [stop, opts2, chg] = psout(optimValues, opts2, flag)
        stop = false; chg = false;
        if strcmp(flag, 'iter')
            history(end+1) = struct('iter', optimValues.iteration, ...
                'fval', optimValues.fval, 'x', optimValues.x(:)');
            if ~isempty(iterFcn)
                iterFcn(struct('iter', optimValues.iteration, 'fval', optimValues.fval, ...
                               'x', optimValues.x(:)', 'names', {names}));
            end
        end
    end

    function stop = outfun(x, ov, state)
        stop = false;
        if strcmp(state, 'iter')
            history(end+1) = struct('iter', ov.iteration, 'fval', ov.fval, 'x', x(:)');
            if ~isempty(iterFcn)
                iterFcn(struct('iter', ov.iteration, 'fval', ov.fval, ...
                               'x', x(:)', 'names', {names}));
            end
        end
    end

fval0 = objective(x0);
switch solver
    case 'patternsearch'
        psOpts = optimoptions('patternsearch', 'Display', 'off', ...
            'MaxIterations', maxIter, 'MaxFunctionEvaluations', 2000, ...
            'OutputFcn', @psout, 'UseParallel', useParallel, ...
            'UseCompletePoll', true);
        [xOpt, fvalOpt] = patternsearch(@objective, x0, [], [], [], [], lb, ub, [], psOpts);
    otherwise
        options = optimoptions('fmincon', 'Algorithm', 'sqp', 'Display', 'off', ...
            'MaxIterations', maxIter, 'MaxFunctionEvaluations', 2000, ...
            'FiniteDifferenceStepSize', 1e-2, 'OutputFcn', @outfun, ...
            'UseParallel', useParallel);
        [xOpt, fvalOpt] = fmincon(@objective, x0, [], [], [], [], lb, ub, [], options);
end
result.solver = solver;

% -- Traces for plotting ------------------------------------------------
[t0, fit0]     = simulate(x0);
[tO, fitOpt]   = simulate(xOpt);

gammaTrue = recoverGamma(xTrue);
gammaOpt  = recoverGamma(xOpt);

    function g = recoverGamma(x)
        sB = sarcB0; sC = sarcC0;
        cp = x(nBag+1:nBag+5)'; phase = x(nBag+6);
        if isSpline
            [sC, sB] = getIntrafusal_pCa_Bspline_5cp_gDynBspline(t, sineStart, MTUfreq, ...
                act_freq, sC, sB, x(1:5)', gDynPhase, cp, phase, ...
                pCaToAct, actToPca, ac.pCaToActB, ac.actToPcaB);
        else
            sB.activating_pCa = x(1);
            [sC, sB] = getIntrafusal_pCa_Bspline_5cp(t, sineStart, MTUfreq, act_freq, ...
                sC, sB, gDynOn, gDynOff, cp, phase, pCaToAct, actToPca);
        end
        g.t = t;
        g.chainPca = sC.pCa(:);      % gamma-static waveform (pCa)
        g.bagPca   = sB.pCa(:);      % gamma-dynamic drive (pCa)
        % control-point markers (at 0,20,40,60,80% of the cycle from perturbStart)
        g.controlTimes = t(sineStart) + phase + [0 .2 .4 .6 .8] * cycle_period;
        g.controlPca   = cp;
        if isSpline
            g.bagControlTimes = t(sineStart) + gDynPhase + [0 .2 .4 .6 .8] * cycle_period;
            g.bagControlPca   = x(1:5)';
        else
            g.bagControlTimes = [];
            g.bagControlPca   = [];
        end
    end

% -- Assemble -----------------------------------------------------------
result.method   = 'bspline';
result.gammaDynamic = gammaDynamic;
result.names    = names;
result.xTrue    = xTrue;
result.x0       = x0;
result.xOpt     = xOpt;
result.lb       = lb;
result.ub       = ub;
result.history  = history;
% Traces are r ABOVE BASELINE (what the cost compares), with the scored window.
result.t        = tgt_t(:);
result.target   = target(:);
result.fit0     = interp1(t0(:), aboveBaseline(fit0), tgt_t(:), 'linear', 'extrap');
result.fitOpt   = interp1(tO(:), aboveBaseline(fitOpt), tgt_t(:), 'linear', 'extrap');
result.scoreWindow = scoreWin;
result.fval0    = fval0;
result.fvalOpt  = fvalOpt;
% Deliberately NO per-parameter recovery score. Any such fraction reads as a
% statement about how well each parameter was identified, and this fit cannot
% support that: the 5 gamma-static control points trade off against each other
% and against the burst, so one moving away from truth while another compensates
% is a perfectly good fit, not a failure of that parameter. The fraction also
% has no value at all when a parameter starts at the answer (zero denominator).
% Report the raw numbers - true, initial, optimized - and the cost, and let the
% drive plots show whether the WAVEFORM was recovered.
result.gammaTrue = gammaTrue;
result.gammaOpt  = gammaOpt;
result.cycle_period = cycle_period;
end


% ======================================================================
function tf = hasParallelToolbox()
% patternsearch/fmincon only honour UseParallel with the Parallel Computing
% Toolbox; asking for it without one warns on every objective evaluation.
tf = ~isempty(ver('parallel')) && license('test', 'Distrib_Computing_Toolbox');
end


function v = getOpt(opts, field, default)
if isfield(opts, field) && ~isempty(opts.(field)), v = opts.(field); else, v = default; end
end
